---
- name: install elasticsearch rpm key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true
- name: Install filebeat
  become: true
  yum:
    name: "/tmp/filebeat-{{ filebeat_version }}-x86_64.rpm"
    state: present
  notify: restart filebeat
